" Files
set fileformat=unix " Correct line endings
set encoding=UTF-8 " Encoding

" Look and feel
syntax on " Syntax highlighting
set number " Line number next to lines
set relativenumber " But make them relativbe
set scrolloff=8 " Start scrolling before the bottom
set clipboard=unnamed " Use system clipboard
set mouse=a " Allow mouse
set linebreak " Automatic linebreak
set confirm " Confirm before exiting
set showcmd " Show the command currently being written
set wildmenu " Autocomplete command line commands


" Max width
set textwidth=80
set formatoptions+=t
set colorcolumn=81

" Tabbing
set tabstop=4 " 4 space tabs
set shiftwidth=4
set expandtab " Some auto tabbing
set autoindent
set smartindent
set smarttab
set expandtab

" Search
set ignorecase " Case-insensitive search
set smartcase " except when I use an uppercase letter
set hlsearch " Highlight search results

" Plugins
call plug#begin('~/.vim/plugged')

    Plug 'sheerun/vim-polyglot'
    Plug 'mattn/emmet-vim'
    Plug 'tpope/vim-commentary'
    Plug 'dense-analysis/ale'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'APZelos/blamer.nvim'
    Plug 'airblade/vim-gitgutter'

call plug#end()

" Color
colorscheme industry

" CoC
so ~/.vim/coc.vim

" No vim out of date warning when on Ifi servers
let g:coc_disable_startup_warning = 1

